apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maas-operator
  name: maas-operator-tier-viewer-role
rules:
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - tiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - tiers/status
  verbs:
  - get
