# This rule is not used by the project maas-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to myapp.io.odh.maas resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: maas-operator
    app.kubernetes.io/managed-by: kustomize
  name: maasplatform-viewer-role
rules:
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - maasplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - maasplatforms/status
  verbs:
  - get
