# This rule is not used by the project maas-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the myapp.io.odh.maas.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: maas-operator
    app.kubernetes.io/managed-by: kustomize
  name: maasplatform-editor-role
rules:
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - maasplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.io.odh.maas
  resources:
  - maasplatforms/status
  verbs:
  - get
